apiVersion: v1
kind: ConfigMap
metadata:
  name: host-devices
  namespace: kube-system
data:
  config.json: |
    {
      "resourceName": "github.com/everpeace-mydevs",
      "socketName": "everpeace-mydevs.sock",
      "numDevices": 100,
      "hostDevices": [{
        "hostPath": "/dev/mydevs/*",
        "containerPath": "/dev/mydevs/*",
        "permission": "rwm"
      }]
    }
